baseurl: /tsai/
collections:
  tooltips:
    output: false
company_name: Ignacio Oguiza
default_badges:
  colab: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    comments: true
    layout: page
    search: true
    sidebar: home_sidebar
    topnav: topnav
- scope:
    path: ''
    type: tooltips
  values:
    comments: true
    layout: page
    search: true
    tooltip: true
description: Practical Deep Learning for Time Series / Sequential Data library based
  on fastai v2/ Pytorch
exclude:
- vendor
google_analytics: null
google_search: 11230dd821e5ae508
highlighter: rouge
host: 127.0.0.1
kramdown:
  auto_ids: true
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
markdown: kramdown
output: web
plugins:
- jekyll-remote-theme
port: 4000
remote_theme: fastai/nbdev-jekyll-theme
repository: timeseriesAI/tsai
sidebars:
- home_sidebar
site_title: tsai
topnav_title: tsai
use_math: true
